export const TRANSACTION_LIST_TYPES_FILTER_PARAM_NAME = 'transactionTypes';
export const TRANSACTION_LIST_ACCOUNT_FILTER_PARAM_NAME = 'account';
export const TRANSACTION_LIST_CATEGORY_FILTER_PARAM_NAME = 'category';
export const TRANSACTION_LIST_DATE_RANGE_FROM_FILTER_PARAM_NAME = 'from';
export const TRANSACTION_LIST_DATE_RANGE_TO_FILTER_PARAM_NAME = 'to';
