import IconWrapper from 'components/icons/IconWrapper';
import { IIconProps } from 'components/icons/types/iconProps';

export default function TaxiIcon({
    size,
    color,
    className,
    wrapperClassName,
}: IIconProps): JSX.Element {
    return (
        <IconWrapper size={size} className={wrapperClassName}>
            <svg
                viewBox="0 0 64 64"
                xmlns="http://www.w3.org/2000/svg"
                className={className}
                style={{ fill: color }}
            >
                <g>
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M8,56H4a2,2,0,0,1-2-2V46a4,4,0,0,1,4-4H58a4,4,0,0,1,4,4v8a2,2,0,0,1-2,2H54"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M62,48H59a3,3,0,0,1-3-3V42"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M8,42l4.734-7.1A11,11,0,0,1,21.887,30H34.7a11,11,0,0,1,7.461,2.917L52,42"
                    />
                    <circle
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        cx="48"
                        cy="56"
                        r="6"
                    />
                    <circle
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        cx="14"
                        cy="56"
                        r="6"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M6,42v4a4,4,0,0,1-4,4H2"
                    />
                    <polyline
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        points="36.023 30 36.023 26 20 26 20 30"
                    />
                    <circle
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        cx="48"
                        cy="56"
                        r="2"
                    />
                    <circle
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        cx="14"
                        cy="56"
                        r="2"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="42"
                        x2="20"
                        y1="56"
                        y2="56"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="25.023"
                        x2="25.023"
                        y1="30"
                        y2="42"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="29.023"
                        x2="29.023"
                        y1="30"
                        y2="42"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="23"
                        x2="23"
                        y1="47"
                        y2="49"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="25"
                        x2="25"
                        y1="45"
                        y2="47"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="27"
                        x2="27"
                        y1="47"
                        y2="49"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="29"
                        x2="29"
                        y1="45"
                        y2="47"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="31"
                        x2="31"
                        y1="47"
                        y2="49"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="33"
                        x2="33"
                        y1="45"
                        y2="47"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="35"
                        x2="35"
                        y1="47"
                        y2="49"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="37"
                        x2="37"
                        y1="45"
                        y2="47"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="39"
                        x2="39"
                        y1="47"
                        y2="49"
                    />
                    <rect
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        height="20"
                        width="32"
                        x="30"
                        y="2"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="33"
                        x2="39"
                        y1="9"
                        y2="9"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="36"
                        x2="36"
                        y1="9"
                        y2="16"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M42,16V11a2,2,0,0,1,2-2h0a2,2,0,0,1,2,2v5"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="42"
                        x2="46"
                        y1="13"
                        y2="13"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M50,8h0a4.828,4.828,0,0,0,1.414,3.414l1.172,1.172A4.828,4.828,0,0,1,54,16h0"
                    />
                    <path
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        d="M54,8h0a4.828,4.828,0,0,1-1.414,3.414l-1.172,1.172A4.828,4.828,0,0,0,50,16h0"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="58"
                        x2="58"
                        y1="8"
                        y2="16"
                    />
                    <polyline
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        points="42 22 42 26 50 26 50 22"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="44"
                        x2="44"
                        y1="26"
                        y2="35"
                    />
                    <line
                        fill="none"
                        stroke="#000"
                        strokeLinejoin="round"
                        strokeWidth="2px"
                        x1="48"
                        x2="48"
                        y1="26"
                        y2="38"
                    />
                </g>
            </svg>
        </IconWrapper>
    );
}
