export const TRANSACTION_LIST_TYPES_FILTER_PARAM_NAME = 'transactionTypes';
export const TRANSACTION_LIST_ACCOUNT_FILTER_PARAM_NAME = 'account';
export const TRANSACTION_LIST_CATEGORY_FILTER_PARAM_NAME = 'category';
